[package]
name = "lib-telemetry"
version.workspace = true
edition.workspace = true
license = "Apache-2.0"
description = "Telemetry: logging, tracing, and metrics"
keywords = ["telemetry", "logging", "tracing", "fastrace", "rusttp"]
categories = ["development-tools::debugging"]
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
chrono.workspace = true
serde_json.workspace = true
fastrace.workspace = true
fastrace-opentelemetry.workspace = true
opentelemetry.workspace = true
opentelemetry-otlp.workspace = true
opentelemetry_sdk.workspace = true
log.workspace = true

[dev-dependencies]
tempfile = "3"
