[package]
name = "rusttp"
default-run = "rusttp"
description = "Rust starter project template for building REST API (or full-stack application)"
authors.workspace = true
version.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
edition.workspace = true
publish = false

[dependencies]
# Internal crates
libcore = { path = "../libcore" }

# Shared crates
anyhow = { workspace = true }
hyper = { workspace = true }
once_cell = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
uuid = { workspace = true }

# Private crates
axum = { version = "0.8.3", features = ["multipart", "macros", "tracing"] }
build-time = { version = "0.1.3" }
clap = { version = "4.5.35", default-features = false, features = ["derive", "help", "std"] }
dotenvy = { version = "^0.15.7" }
tower = { version = "0.5.2", features = ["buffer", "limit", "util"] }
tower-http = { version = "0.6.2", features = ["timeout", "trace", "fs", "cors", "request-id", "normalize-path", "compression-full"] }
tower-layer = { version = "0.3.3" }
tower-service = { version = "0.3.3" }
