[package]
name = "lib-queue"
version.workspace = true
license = "Apache-2.0"
description = "Job queue utilities"
keywords = ["queue", "jobs", "rusttp"]
categories = ["web-programming", "database"]
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true
edition.workspace = true
publish = false

[lib]
name = "lib_queue"
path = "src/lib.rs"

[dependencies]
serde.workspace = true
thiserror.workspace = true
