[package]
name = "lib-mailer"
version.workspace = true
edition.workspace = true
license = "Apache-2.0"
description = "Email sending utilities"
keywords = ["email", "mailer", "rusttp"]
categories = ["email", "web-programming"]
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
serde.workspace = true
thiserror.workspace = true
