[package]
name = "lib-mailer"
version.workspace = true
license = "Apache-2.0"
description = "Email sending utilities"
keywords = ["email", "mailer", "rusttp"]
categories = ["email", "web-programming"]
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true
edition.workspace = true
publish = false

[lib]
name = "lib_mailer"
path = "src/lib.rs"

[dependencies]
serde.workspace = true
thiserror.workspace = true

[lints.rust]
linker_messages = "allow"
