[package]
name = "lib-observer"
version.workspace = true
license = "Apache-2.0"
description = "Observer: logging, tracing, and metrics"
keywords = ["telemetry", "logging", "tracing", "fastrace", "rusttp"]
categories = ["development-tools::debugging"]
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true
edition.workspace = true
publish = false

[lib]
name = "lib_observer"
path = "src/lib.rs"

[dependencies]
chrono.workspace = true
fastrace-opentelemetry.workspace = true
fastrace.workspace = true
log.workspace = true
logforth.workspace = true
opentelemetry-otlp.workspace = true
opentelemetry.workspace = true
opentelemetry_sdk.workspace = true
serde.workspace = true
serde_json.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints.rust]
linker_messages = "allow"
