[package]
name = "rusttp"
version.workspace = true
license = "Apache-2.0"
description = "Rusttp — Axum web application"
keywords = ["axum", "web", "api", "rusttp"]
categories = ["web-programming", "web-programming::http-server"]
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true
edition.workspace = true
publish = false

[[bin]]
name = "rusttp"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
axum.workspace = true
chrono.workspace = true
clap.workspace = true
fastrace = { workspace = true, features = ["enable"] }
fastrace-axum.workspace = true
lib-observer = { path = "../crates/lib-observer" }
log.workspace = true
rand.workspace = true
rust-embed.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tower-http.workspace = true

[target.'cfg(not(target_env = "msvc"))'.dependencies]
libmimalloc-sys = { version = "0.1", default-features = false, features = ["extended"] }
mimalloc = { version = "0.1.52", default-features = false }

[dev-dependencies]
tower.workspace = true

[build-dependencies]
chrono.workspace = true

[lints.rust]
linker_messages = "allow"
