[package]
name = "identity"
version.workspace = true
license = "Apache-2.0"
description = "Authentication and session management"
keywords = ["auth", "identity", "sessions", "rusttp"]
categories = ["authentication", "web-programming"]
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true
edition.workspace = true
publish = false

[lib]
name = "mod_identity"
path = "src/lib.rs"

[dependencies]
anyhow.workspace = true
chrono.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
uuid.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["rt", "macros"] }
